site_name: low level
markdown_extensions: [math]
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- Home: index.md
- Computer:
  - Formats: formats.md
  - Architectures: arch.md
  - Embedded Systems: embedded.md
  - Shells: shell.md
  - Filesystem: filesystem.md
- Programming:
  - Home: programming.md
  - Data structures: data_structures/index.md
  - Ptrace: ptrace.md
  - Randomness: randomness.md
  - Memory: memory.md
- Security:
  - 'Home': security.md
  - 'Crypto': security/crypto.md
  - 'XXE': security/xxe.md
  - 'XSS': security/xss.md
  - 'CVE': cve.md
  - 'Hardware': security/hardware.md
  - 'Video':    security/video.md
  - Remote code execution: security/rce.md
  - Shellcode: shellcode.md
  - Counter measure: counter-measure.md
- Reversing:
  - Home: reversing/reversing.md
  - Radare2: reversing/radare2.md
- Networking:
  - Home: networking.md
  - Iptables: networking/iptables.md
- Computer vision: cv.md
theme: readthedocs
