site_name: low level
markdown_extensions: [math]
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- [index.md, Home]
- [formats.md, Formats]
- [arch.md, Architectures]
- [shell.md, Shells]
- [filesystem.md, Filesystem]
- [programming.md, Programming]
- [ptrace.md, Ptrace]
- [security.md, Security]
- [cve.md, CVE]
- [randomness.md, Randomness]
- [reversing.md, Reversing]
- [shellcode.md, Shellcode]
- [data_structures/index.md, Data structures]
- [networking.md, Networking]
theme: readthedocs
