site_name: low level
markdown_extensions: [math]
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- Home: index.md
- Computer:
  - Formats: formats.md
  - Architectures: arch.md
  - Shells: shell.md
  - Filesystem: filesystem.md
- Programming:
  - Home: programming.md
  - Data structures: data_structures/index.md
  - Ptrace: ptrace.md
  - Randomness: randomness.md
- Security:
  - 'Home': security.md
  - 'XXE': security/xxe.md
  - 'CVE': cve.md
  - Remote code execution: security/rce.md
  - Reversing: reversing.md
  - Shellcode: shellcode.md
- Networking:
  - Home: networking.md
theme: readthedocs
